### ISSUE TITLE
How to correct Tn5 insertions?

### ISSUE THREAD

**Issue by Fuyt27** [yal054/snATACutils#2]
Hello!
I wonder how to  correct Tn5 insertions (reads aligned to the positive strand were shifted +4 bp and reads aligned to the negative strand were shifted –5 bp) before the step of peak calling. This step seems to be unavailable in the provided scripts.
I would appreciate it for your reply!

**Comment by yal054** [comment]
Hi @Fuyt27 , thank you for your interests! 
please reference the section called `03.peak_calling` in my pipeline. 

basically, once you got the sequencing reads in bedpe format, you can follow these steps to correct the Tn5 insertions: 
```{bash}
zcat ${your_bedpe.gz} | awk 'BEGIN{OFS="\t"}{printf "%s\t%s\t%s\tN\t1000\t%s\n%s\t%s\t%s\tN\t1000\t%s\n",$1,$2,$3,$9,$4,$5,$6,$10}' | gzip -c > ${your_tagAlign.gz}
zcat ${your_tagAlign.gz} | awk 'BEGIN{OFS=FS="\t"}{ if ($6 == "+") {$2 = $2 + 4} else if ($6 == "-") {$3 = $3 - 5} print $0}' | gzip -nc > ${your_tnf5_corrected_tag.gz}
```

**Comment by Fuyt27** [comment]
Thanks for your reply! I am sorry for having missed something important in your pipeline.
and  I have another question: whether the fragment(chrom,start,end) in the snap files needs to be tn5-corrected

what if I have to do the Tn5 corrections in the aligned (by snaptools)bam file instead of bed file.
I have tried ATACseqQC(R package),but it is not suitable for large files

**Comment by yal054** [comment]
sure, you can definitely correct the Tn5 insertions in bam file.
In that case, maybe worth to write a script with the help from `pysam`

**Comment by Fuyt27** [comment]
> sure, you can definitely correct the Tn5 insertions in bam file.
> In that case, maybe worth to write a script with the help from `pysam`

Thank you!

**Comment by Fuyt27** [comment]
I previously thought that snaptools could function as correcting the tn5 insertion,besides filtering properly paired and unique mapped reads as well as removing PCR duplicate. And now I know I might do the correction with Pysam. Thanks for your patient reply!
